### ISSUE TITLE
Change the name of the tab to reflect the name of the  method

### ISSUE THREAD

**Issue by simonsantama** [fire-library/openfire#1]
What it does now: All tabs are named "Index".
What it should do: The tabs should show the name (Title) of the method. "Ventilation factor"

**Comment by JamieMaclean** [comment]
@simonsantama, are we sure about this? I agree that it should not be "Index", that should change. But the current behaviour is to show the name of the file that the method has been saved to, similar to VSCode etc. Lets discuss in one of our catchups.

**Comment by JamieMaclean** [comment]
Addressed by https://github.com/fire-library/openfire/pull/20
