### ISSUE TITLE
Implement HRR at flashover

### ISSUE THREAD

**Issue by simonsantama** [fire-library/openfire#10]
Name: HRR at Flashover
Reference: PD 7974-1:2019.
Equation 1: Section 8. Equation 28. Method by Thomas.
Equation 2: Section 8. Equation 29. Method by McCaffrey et al.
Equation 3: Section 8. Equation 33. Method by Kawago

**Comment by JamieMaclean** [comment]
@simonsantama I've created the equations here but I'm not sure what I'm supposed to be implementing. The input is common for all of them so do I calculate all 3 at the same time and do a comparison? What is the output here?

**Comment by simonsantama** [comment]
Yes. Three different equations. You can use only one or ideally all of them
at the same time. Output is the independent HRR values

**Comment by JamieMaclean** [comment]
Addressed. PR of implementation: https://github.com/fire-library/openfire/pull/21/files
