### ISSUE TITLE
Implement Harmathy's correlation for regime of burning

### ISSUE THREAD

**Issue by simonsantama** [fire-library/openfire#13]
Document: Chapter 10. Introduction to fire dynamics
Equations 10.18a and 10.18b

**Comment by JamieMaclean** [comment]
@simonsantama same here. What is the output of this method? 

I assume it would be whether it is "fuel controlled", "ventilation controlled" or in the "crossover"?

**Comment by simonsantama** [comment]
Yes. The output is the identification of fuel controlled or ventilation
controlled

**Comment by JamieMaclean** [comment]
Done in these two PRs: https://github.com/fire-library/openfire/pull/25 and https://github.com/fire-library/openfire/pull/22
