### ISSUE TITLE
Add a section to add the full reference to the method

### ISSUE THREAD

**Issue by simonsantama** [fire-library/openfire#23]
This could be a block at the end of the input or calculation tabs or even a new tab that is just called "reference" and it adds the reference to the document in full Harvard (or whatever we decide to use) format.

If you create the space for it, then I can add the actual information for all the methods.

**Comment by JamieMaclean** [comment]
Sure thing. I always found this one difficult to place but now that we've moved to rust it totally just belongs in the trait. I'll add a function to return the full reference and on the front end we can add the classic button to "copy to clipboard"

**Comment by simonsantama** [comment]
Amazing
