### ISSUE TITLE
Add functionality to download the calculation sheet

### ISSUE THREAD

**Issue by simonsantama** [fire-library/openfire#5]
What it does now: No downloading
What it should do: If easy, download as PDF. Otherwise, some option to download.

**Comment by JamieMaclean** [comment]
This one is not a small task. I would say that we stick this as a milestone for V2... Sooner if we get feedback that it is a must have.

**Comment by simonsantama** [comment]
Yeh I remember our previous discussions on this. What would they do at the moment? Can the save it as a html or would they need to a screenshott?
